# Generated by Django 4.0.6 on 2022-07-13 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='link_redirecionado',
            new_name='linkredirecionado',
        ),
    ]
