# Generated by Django 4.0.6 on 2022-07-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0003_rename_linkredirecionado_links_link_redirecionado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='link_redirecionado',
            new_name='linkredirecionado',
        ),
    ]
