# Generated by Django 4.0.6 on 2022-07-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0004_rename_link_redirecionado_links_linkredirecionado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='linkredirecionado',
            new_name='link_redirecionado',
        ),
    ]
