name: Django CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_DB: encurtador
          POSTGRES_USER: encurtador
          POSTGRES_PASSWORD: encurtador
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        ports: [ '5432:5432' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Instalar dependências
      run: |
        pip install -r requirements-dev.txt
    - name: Lint com Flake8
      run: |
        flake8
    - name: Test com Pytest
      run: |
        pytest encurtador